# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
#    - name: Stop service
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.HOME_HOST }}
#        port: ${{ secrets.HOME_PORT }}
#        key: ${{ secrets.HOME_PRIVATE_KEY}}
#        script: service dorfbot stop
    - name: Transfer program files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOME_HOST }}
        port: ${{ secrets.HOME_PORT }}
        username: ${{ secrets.HOME_USER }}
        key: ${{ secrets.HOME_PRIVATE_KEY }}
        source: ./build/distributions/dorfbot.zip
        target: /opt/bots/dorf/dorfbot.zip
        rm: true
    - name: Unzip program files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOME_HOST }}
        port: ${{ secrets.HOME_PORT }}
        username: ${{ secrets.HOME_USER }}
        key: ${{ secrets.HOME_PRIVATE_KEY}}
        script: unzip -o /opt/bots/dorf/dorfbot.zip